version: '3.8'

services:
  web:
    build: .
    container_name: dreamview-web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
